architecture: replication

auth:
  enabled: true
  password: "redis"

sentinel:
  enabled: true
  masterSet: mymaster
  downAfterMilliseconds: 5000
  failoverTimeout: 10000
  service:
    type: ClusterIP

master:
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  service:
    type: ClusterIP

replica:
  replicaCount: 3
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  service:
    type: ClusterIP

podAntiAffinityPreset: soft