apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-kraft
  namespace: data
  labels:
    role: data
spec:
  containers:
    - name: plane
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - name: title
          containerPort: 80
          protocol: TCP
  restartPolicy: Always
  