apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      name: kafka-producer
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: yeonwu/kafka-producer:latest
          imagePullPolicy: Always
