version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk-net
    env_file:
      - ../../.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u $ES_USERNAME:$ES_PASSWORD http://localhost:9200/_cluster/health | grep -E '\"status\":\"(green|yellow)\"' >/dev/null"]
      timeout: 5s
      retries: 30
      start_period: 60s


  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    environment:
      - LOGSTASH_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/conf.d:/usr/share/logstash/pipeline
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "9600:9600"
    networks:
      - kafka-net
      - elk-net
    env_file:
      - ../../.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9600/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 20s


  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    networks:
      - elk-net
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD-SHELL", "curl -sI http://localhost:5601 | grep -E ' 200| 302' >/dev/null"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  es-data:

networks:
  elk-net:
    external: true
    driver: bridge
  kafka-net:
    external: true
