spring:
  profiles:
    active: local
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        linger.ms: 5
        partitioner.class: org.apache.kafka.clients.producer.internals.DefaultPartitioner
      client-id: kafka-producer

    bootstrap-servers:
      - kafka-broker1:29092
      - kafka-broker2:29093
      - kafka-broker3:29094