spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  amadeus:
    api:
      client-id: ${AMADEUS_CLIENT_ID}
      client-secret: ${AMADEUS_CLIENT_SECRET}

  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        nodes:
          - my-redis-node-0.my-redis-headless.data.svc.cluster.local:26379
          - my-redis-node-1.my-redis-headless.data.svc.cluster.local:26379
          - my-redis-node-2.my-redis-headless.data.svc.cluster.local:26379

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refreshExpiration: ${JWT_REFRESH_EXPIRATION}

server:
  port: 8080