version: "3.8"

services:
  redis-node-1:
    image: redis:7.2
    container_name: redis-node-1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7001:6379"
      - "17001:16379"
    volumes:
      - ./redis/7001:/usr/local/etc/redis
      - redis-node-1-data:/data
    networks:
      - redis-cluster-net


  redis-node-2:
    image: redis:7.2
    container_name: redis-node-2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7002:6379"
      - "17002:16379"
    volumes:
      - ./redis/7002:/usr/local/etc/redis
      - redis-node-2-data:/data
    networks:
      - redis-cluster-net


  redis-node-3:
    image: redis:7.2
    container_name: redis-node-3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7003:6379"
      - "17003:16379"
    volumes:
      - ./redis/7003:/usr/local/etc/redis
      - redis-node-3-data:/data
    networks:
      - redis-cluster-net


  redis-node-4:
    image: redis:7.2
    container_name: redis-node-4
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7004:6379"
      - "17004:16379"
    volumes:
      - ./redis/7004:/usr/local/etc/redis
      - redis-node-4-data:/data
    networks:
      - redis-cluster-net


  redis-node-5:
    image: redis:7.2
    container_name: redis-node-5
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7005:6379"
      - "17005:16379"
    volumes:
      - ./redis/7005:/usr/local/etc/redis
      - redis-node-5-data:/data
    networks:
      - redis-cluster-net


  redis-node-6:
    image: redis:7.2
    container_name: redis-node-6
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7006:6379"
      - "17006:16379"
    volumes:
      - ./redis/7006:/usr/local/etc/redis
      - redis-node-6-data:/data
    networks:
      - redis-cluster-net

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:

networks:
  redis-cluster-net:
    name: redis-cluster-net
    driver: bridge