persistence:
  enabled: true
  accessMode: "ReadWriteOnce"
  size: "10Gi"
controller:
  adminSecret: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1"