kafka-broker3:
  image: confluentinc/cp-kafka:7.4.3
  container_name: kafka-broker3
  ports:
    - "9094:29092"
  environment:
    KAFKA_BROKER_ID: 3
    KAFKA_ZOOKEEPER_CONNECT: <broker1 서버 IP>.com:2181
    KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://<개별 서버 IP>:9092
    KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker3:9092,EXTERNAL://<개별 서버 IP>:29092
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    KAFKA_MIN_INSYNC_REPLICAS: 2
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
    KAFKA_LOG_DIRS: /var/lib/kafka/kafka-logs-3
  volumes:
    - kafka-data-3:/var/lib/kafka
  networks:
    - kafka-net
