apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-service
  namespace: apps
  labels:
    app: elasticsearch-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: elasticsearch-service
    spec:
      containers:
        - name: elasticsearch-service
          image: yeonwu/es-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ES_URI
              value: https://elastic-es-http.data.svc.cluster.local:9200
            - name: ES_USERNAME
              value: elastic
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-es-elastic-user
                  key: elastic

            - name: SPRING_SSL_BUNDLE_PEM_ES_TRUSTSTORE_CERTIFICATE
              value: /etc/es/certs/ca.crt
            - name: SPRING_ELASTICSEARCH_SSL_BUNDLE
              value: es

          envFrom:
            - secretRef:
                name: app-secret

          volumeMounts:
            - name: es-ca
              mountPath: /etc/es/certs
              readOnly: true

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi

      volumes:
        - name: es-ca
          secret:
            secretName: elastic-es-http-certs-public