apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels: { app: api-server }
  template:
    metadata:
      labels: { app: api-server }
    spec:
      containers:
        - name: api-server
          image: yeonwu/skytracker-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secret
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-redis
                  key: redis-password