apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: apps
  labels:
    app: elasticsearch-service
spec:
  selector:
    app: elasticsearch-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  