apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: apps
  labels:
    app: api-server
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  